#/bin/bash

# all variables used in ps1 files
PROJECT_NAME="shoora"
PROJECT_ROOT_DIR_PATH="/home/mohnish/Desktop/personal-projects/shoora"

PROJECT_ROOT_PATH_RELATIVE_FROM_SCRIPT="../.."
BUILD_FOLDER_NAME="bin"
SRC_FOLDER_NAME="src"
BUILD_SCRIPTS_RELATIVE_PATH="build_scripts/linux"
CHAPTER_SUBFOLDERS_BUILD_FOLDER_NAME="bin"

BIN_DIR_PATH="$PROJECT_ROOT_DIR_PATH/$BUILD_FOLDER_NAME"
SRC_DIR_PATH="$PROJECT_ROOT_DIR_PATH/$SRC_FOLDER_NAME"
BUILD_SCRIPTS_DIR_PATH="$PROJECT_ROOT_DIR_PATH/$BUILD_SCRIPTS_RELATIVE_PATH"